title: Ayush Saxena
description: <img src ="https://media.licdn.com/dms/image/D4D03AQH3jAKBOPyAFA/profile-displayphoto-shrink_400_400/0/1672828965757?e=1693440000&v=beta&t=j75odXP-XaKMJRX97HSBUWozSmkCZ5uoJccgEwVHTrw">Passionate about leveraging cutting-edge machine learning algorithms and deep learning architectures to solve complex problems and drive innovation.
show_downloads: false
google_analytics:
theme: jekyll-theme-dinky
